### ISSUE TITLE
spec(Rewrite all tests to use tape.js)

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/jquery-csv#101]
# Rewrite all tests to use tape.js

Mocha + chai needs to be retired. It's too bloated, introduces globals, and won't work for browser testing without significant effort. Tape.js will be a better alternative going forward.

## Goals

- setup tape
- rewrite all tests
- split tests up into different files

## Milestones

- [x] install tape.js + reporter
- [x] update test script
- [x] test $.csv.toArray()
- [x] test $.csv.toArrays()
- [x] test $.csv.fromArray()
- [x] test $.csv.fromArrays()
- [x] test RFC compliance
- [x] test RFC amendments
- [x] test options
- [x] test edge cases
- [x] test $.csv.parsers

**Comment by evanplaice** [comment]
Milestones completed and included in v0.8.9
