### ISSUE TITLE
spec(Create New Demo Template and Migrate the Existing Examples to it)

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/jquery-csv#121]
# Create New Demo Template and Migrate the Existing Examples to it

The existing examples aren't necessarily easy to follow. The core methods are all lumped into the Basic Usage Demo, and the rest are a disjointed mix of one-off implementations.

This Spec is intended to create a very minimal Demo template and migrate all existing examples to it.

## Milestones

- [x] Create a Demo Template
- [x] Migrate toArray()
- [x] Migrate toArrays()
- [x] Migrate fromArrays()
- [x] Migrate toObject()
- [x] Migrate toObjects()
- [x] Migrate fromObjects()
- [x] Migrate Flot Demo
- [x] Migrate Google Visualization API Demo
- [x] Migrate File-Handling Demo
- [x] Delete Basic Usage Demo
- [x] Update README to link to new demos
- [x] Add AJAX Handling Demo

**Comment by evanplaice** [comment]
Implemented in 0.8.13
