### ISSUE TITLE
roadmap(1.0.0) No new features. Fix all the things.

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/jquery-csv#92]
Project:
- [x] [Make Jquery-CSV Contributor-Friendly](https://github.com/evanplaice/jquery-csv/issues/95)
- [x] Add Style Checking Support
- [x] Add Travis-CI support
- [x] Add .npmignore to trim down package size

Documentation:
- [x] Update badges on README.md
- [x] [Document ESM Import Usage](https://github.com/evanplaice/jquery-csv/issues/93)
- [x] [Update Node usage](https://github.com/evanplaice/jquery-csv/issues/68)
- [x] [Document Date Parsing User Defined Callback](https://github.com/evanplaice/jquery-csv/issues/94)

Examples:
- [x] Add fromArrays() Demo
- [x] Add fromObjects() Demo
- [x] [Create New Demo Template and Migrate the Existing Examples to it](https://github.com/evanplaice/jquery-csv/issues/121)

Features:
- [x] [Configurable Line Ending](https://github.com/evanplaice/jquery-csv/issues/100)

Testing:
- [x] Add Travis-CI support
- [x] [Rewrite all tests to use tape.js](https://github.com/evanplaice/jquery-csv/issues/101)
- [x] [Add Missing tests](https://github.com/evanplaice/jquery-csv/issues/120)
- [x] [Add onPreParse() Tests](https://github.com/evanplaice/jquery-csv/pull/130)
- [x] [Add onParseEntry() Tests](https://github.com/evanplaice/jquery-csv/pull/132)
- [x] [Add onParseValue() Tests](https://github.com/evanplaice/jquery-csv/pull/131)
- [x] [Add onPostParse() Tests](https://github.com/evanplaice/jquery-csv/pull/124/files)

Bugs:
- [x] #78 Split lines does not work if options is not passed
- [x] ~~#84 \ in csv will return as \\~~
- [x] ~~#72 csv.toArrays(data) working but last csv input data missing in Array~~
- [x] #70 bug fix in $.csv.fromArrays()
- [x] #64 onPostParse's callback return value has no effect
- [x] ~~#58 toObjects onParseEntry returns string instead of object~~
- [x] ~~#57 Fix fromArrays for multiple delimiters~~
- [x] ~~#51 Change hooks to check against `null` when no hook is specified~~
- [x] #48 Options arg not really optional?
- [x] ~~#38 colNum not reset when onParseValue callback called~~
