### ISSUE TITLE
spec(Make Jquery-CSV Contributor-Friendly)

### ISSUE THREAD

**Issue by evanplaice** [evanplaice/jquery-csv#95]
# Make Jquery-CSV Contributor-Friendly

This project is too widely used<sup>1</sup> to be supported by a single dev. It's about damn time to open it up for outside contribution. Specifically, I intend to make this project more friendly for contributors who are new and/or less experienced with working on OSS.

*<sup>1</sup> 500K downloads prior to the migration from Google Code, avg 1000 downloads/month via NPM. Who knows how many from other sources (ex CDNJS, Bower, etc)*

## Goals

- Provide scaffolding to document intended changes
- Market the project as contributor-friendly
- Create opportunities to help other devs grow
- Fix some major structural issues with the project (ex testing)
- Address as many of the existing bugs as possible

## Milestones

- [x] Update [CONTRIBUTING.md][CONTRIBUTING.md]
- [x] Add [ISSUE_TEMPLATE.md][ISSUE_TEMPLATE.md]
- [x] Add [PULL_REQUEST_TEMPLATE.md][PULL_REQUEST_TEMPLATE.md]
- [x] Add [SPEC_TEMPLATE.md][SPEC_TEMPLATE.md]
- [x] Add [FEAT_TEMPLATE.md][FEAT_TEMPLATE.md]
- [x] Add the project to the [Up-For-Grabs.net][Up-For-Grabs.net]
- [x] Add the project to [CodeTriage.com][CodeTriage.com]

## Details

Time to breathe some life back into this project.

This project initially took off for a few reasons:

- There were no good (ie RFC compliant) alternatives at the time
- I spent a very significant amount of promoting it across the web
- I was passionate and had lots of time to dedicate to project maintenance (ie documentation, testing, etc)

It exists, and is used in an extremely wide array of applications but it's not good enough to rely on inertia alone. 6 years later and a lot as changed. I have aspirations to take this project in the future but the qualities that made this project good to begin with are no longer possible. It's time for a new direction.

The new goals are as follows:

- Open the project to the wider OSS community
- Ask for help from the community
- Use the project as a jump-off point to help other devs improve

In a way, this project exists as a social experiment. At first, to see if it could reach critical mass via grassroots promotion. Now, to see if this project can advance from a sad single developer burden to community driven awesomeness.

If this experiment is a success - and by success I mean better code, better testing, community support - this project will be in a good place to move forward to the next phase.

The future:

- Migrate to an organization to share ownership with others
- Drop reliance on jquery
- Rename the project
- An ES6+ rewrite
- Make the source easier to read, modify, maintain
- Consolidate the 2 internal parser implementations into 1

[Contributing.md]: https://github.com/evanplaice/jquery-csv/blob/master/CONTRIBUTING.md
[ISSUE_TEMPLATE.md]: https://github.com/evanplaice/jquery-csv/blob/master/.github/ISSUE_TEMPLATES/ISSUE_TEMPLATE.md
[PULL_REQUEST_TEMPLATE.md]: https://github.com/evanplaice/jquery-csv/blob/master/.github/ISSUE_TEMPLATES/PULL_REQUEST_TEMPLATE.md
[SPEC_TEMPLATE.md]: https://github.com/evanplaice/jquery-csv/blob/master/.github/ISSUE_TEMPLATES/SPEC_TEMPLATE.md
[FEAT_TEMPLATE.md]: https://github.com/evanplaice/jquery-csv/blob/master/.github/ISSUE_TEMPLATES/FEAT_TEMPLATE.md
[Up-For-Grabs.net]: https://github.com/up-for-grabs/up-for-grabs.net/pull/863
[CodeTriage.com]: https://www.codetriage.com/evanplaice/jquery-csv

**Comment by evanplaice** [comment]
Ran into a snag. According to the [GitHub Documentation](https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/), I should be able to create issues from an arbitrary template using url parameters.

Example:
- https://github.com/evanplaice/jquery-csv/issues/new?template=SPEC_TEMPLATE.md&title=spec()&labels=specification

Except the `template` parameter isn't working. I sent a message to GitHub, and am waiting for a response back.

I really hope I can get this working because it should be trivial to add these links to CONTRIBUTING.md for so that contributors can quickly/easily create context-specific issues, document intent, without any additional cognitive stress.
